---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Render nginx site config
  ansible.builtin.template:
    src: lunch.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_site_name }}.conf"
    mode: "0644"
  notify: Reload nginx

- name: Enable site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nginx_site_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_site_name }}.conf"
    state: link
    force: yes
  notify: Reload nginx

- name: Disable default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Nginx config test
  ansible.builtin.command: nginx -t
  changed_when: false

- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
